### ISSUE TITLE
Invalid SSL cert

### ISSUE THREAD

**Issue by venning** [staticmanapp/roadmap#3]
staticman.net has an SSL certificate (or certificate chain) that throws an error on Android Chrome.

Chrome won't let you proceed without declaring you want to proceed to an "UNSAFE" website.

**Comment by eduardoboucas** [comment]
Thanks! I'm looking into this.

**Comment by eduardoboucas** [comment]
@venning This should be fixed now. Are you able to check?

**Comment by venning** [comment]
The HTTPS URL is loading correctly on Android Chrome now.  However, when I go to the HTTP version of the URL, it does not redirect me to HTTPS.

I don't know if that's intentional, but as long as you offer an HTTPS site you may as well direct people.  Considering you are offering to take some of their content, having HTTPS brings peace of mind, and it also is supposed to be a positive signal in Google's search algorithm.

**Comment by eduardoboucas** [comment]
It was not intentional, it has been fixed now. Thanks for your help!
